export const resetToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsIm5hbWUiOiJNaWd1ZWwgQXRodXIgc3NzcyIsImVtYWlsIjoibWlndWVsQGdtYWlsLmNvbSIsImlhdCI6MTczOTY2NzM4OCwiZXhwIjoxNzQwMjcyMTg4LCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMTEifQ.pD5sDnHGYD2aKE1jXv9DXWs_166PLBxLDcoZ22r3dQM';
